### ISSUE TITLE
OHBM OSR

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#102]
Submissions to the open science room close April 10th (https://ohbm.github.io/osr2020/submit/)! 

Did you submit something @edickie?

**Comment by josephmje** [comment]
Thanks @arokem. Will post the abstract for discussion today.

**Comment by josephmje** [comment]
Editable version here: shorturl.at/BMNSV

**Title:** dMRIPrep - A Robust and Reproducible Pipeline for dMRI data Pre-Processing

**Collaborators:**
https://github.com/nipreps/dmriprep/graphs/contributors
Adam Richie-Halford
Anisha Keshavan
Michael Joseph
Garikoitz Lerma-Usabiaga
Derek Pisner
Matthew Cieslak
Erin Dickie
Jelle Veraart
Ross Lawrence
Ariel Rokem
Oscar Esteban

**Theme:** Open Workflows

**Presentation Format:** Lightning talk OR Software/process demo (not sure which direction we should go with)

**Links:**
https://github.com/nipreps/dmriprep

**Abstract (max 200 words):**

dMRIPrep is an analysis-agnostic pipeline that seeks to address the challenge of robust and reproducible pre-processing for whole-brain dMRI data. The pipeline is based on Nipype and encompasses a large set of tools from other neuroimaging packages. It performs basic preprocessing steps such as head-motion correction, susceptibility-derived distortion correction, eddy current correction, etc., providing outputs that can be easily submitted to a variety of diffusion models. This pipeline was designed to provide the best software implementation for each state of preprocessing, and will be continually updated as better methods becomes available.

The Open Science Room is an excellent venue for dMRI enthusiasts to meet. We would like to demo dMRIPrep's core functionality and seek testing, feedback and contributions from the neuroimaging community. This talk will contain an interactive overview of dMRI data pre-processing with dMRIPrep, as well as highlight some novel methods being developed.

**Comment by arokem** [comment]
Looks great! I just fixed a small typo, but I think this is ready to go.

@josephmje : are you going to do the submission?

**Comment by josephmje** [comment]
> Looks great! I just fixed a small typo, but I think this is ready to go.
> 
> @josephmje : are you going to do the submission?

Thanks for the edits @arokem! Yes, I can submit.

**Comment by arokem** [comment]
Awesome. Closing

**Comment by josephmje** [comment]
Our OSR talk has been accepted. They have asked to book a time for recording the talk at [this link](https://docs.google.com/spreadsheets/d/1DDMmf43skC_EyD8hDRTO5r6SYy0QkmyfzPNtAz3eWiw/edit#gid=938092993). I have temporarily booked Saturday June 6th at 11 am Mountain Time. However, I can change this to our typical meeting time on Tuesday if people like.

Also, I wasn't aware of this but all speakers in the OSR are required to be registered for OHBM. I am not sure if I am attending yet. I was only planning on going for the ReproNim fellowship and OHBM Hackathon.

**Comment by edickie** [comment]
@josephmje I think you should count in our lab's group registration this year. So wouldn't worry about that..

**Comment by oesteban** [comment]
@nipreps/dmriprep - link for the videocall tomorrow (12.30pm PST) - https://stanford.zoom.us/j/91491481620

**Comment by josephmje** [comment]
link for the recording tomorrow (10 am PST, 1 pm EST) - https://us02web.zoom.us/j/86518248310?pwd=c0hyUEpBQkpNMDdiRkhLWldHSEpKQT09
