### ISSUE TITLE
fieldmap-free distortion correction

### ISSUE THREAD

**Issue by h-w-k** [nipreps/dmriprep#111]
* dmriprep version: 0.2.2
* Python version: 2.7.15
* Operating System: centos 6

Dear all, 
I am writing to seek your expertise and advices on fieldmap-less distortion correction in DMRIPREP.

I executed the following commandline.
“singularity run --cleanenv -B /home/BIDS_output:/work -B /home/DMRIPREP_output:/output -B /home:/main /home/dmriprep-0.2.2.simg /work /output participant --participant_label sub-2475376 --fs-license-file /main/license.txt --use-syn-sdc -skip-bids-validation -w /main/WORK”

It seems no processing in the distortion correction as shown in the report.html 

“Errors
No errors to report!”

“Diffusion
Average b=0 that serves for reference in early preprocessing steps.”

Then no more steps and no dwi folder is generated.

May i know how to make it successfully run?

In addition, the following remark is shown in the log throughout the whole processing.

“200608-08:24:28,893 nipype.utils WARNING:
Could not check for version updates:
Connection to server could not be made”

Would it affect the products? How to fix it?

Thank you very much.

Best regards,
Winky

**Comment by oesteban** [comment]
Hi Winky, currently we're a bit far from being able to run any sort of fieldmap-less distortion correction. We'll work on a better SDC integration as soon as possible.

**Comment by h-w-k** [comment]
Hi Oesteban, thank you very much for your reply and all the effort from the development team. 

I am working on the project that does not include reversed DTI for distortion correction. Now, I try to go through the fieldmap-less distortion correction in DTI (using ANTs and T1w image) stated in the following paper before DMRIPREP is enriched. Do you have any suggestions or advices?
 
Evaluation of Field Map and Nonlinear Registration Methods for Correction of Susceptibility Artifacts in Diffusion MRI, available at 
https://www.frontiersin.org/articles/10.3389/fninf.2017.00017/full

**Comment by effigies** [comment]
@oesteban I see some syn-related parameters in the config. Is this enabled?

**Comment by oesteban** [comment]
Unfortunately, it is not.
