### ISSUE TITLE
Meeting 09/29 - Agenda

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#118]
Pre:
  - [x] @arokem - could you generate a new recurring meeting zoom link so next time we are not cut off after 40 minutes?
  - [x] @josephmje will put together a tutorial proposal for ISBI 2021 ([deadline: 09/25](https://biomedicalimaging.org/2021/)).

Agenda:

  - Proposal for BrainHack Donostia: @oesteban will report back after meeting with @CesarCaballeroGaudes and @eurunuela:
    - Interest on dMRIPrep
    - Will there be timezones?
- BIDS/IntendedFor/FieldMap correction strategies: perhaps we need a wide extension of BIDS to support sophisticated DWI protocols? - Follow up on #43 and check bids-standard/bids-2-devel#39 before for context.

**Comment by arokem** [comment]
You should have received a calendar invite with a new zoom link (this one has a washington.zoom.us URL).
