### ISSUE TITLE
Tutorial Proposal for ISBI (deadline: 09/25)

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#119]
@josephmje how are we doing on this front?

**Comment by josephmje** [comment]
Thanks for the poke @oesteban . My apologies, I should have shared my notes earlier. Here's a [link](https://docs.google.com/document/d/1pl1X6IxVmjhcv0svXCTPJJPn5L3e_yT-IHsykk0wHYc/edit?usp=sharing) to the Google Doc. I thought of some potential topics to cover under the "Brainstorming Topics" heading. If you have any more, please add them there. I can then expand on the rest of the required information.

**Comment by oesteban** [comment]
Paging @garikoitz.

@josephmje - it seems we can't edit or comment.

**Comment by josephmje** [comment]
Just updated the permissions. Can you please check if it works now?

**Comment by oesteban** [comment]
It works now - thanks!

**Comment by josephmje** [comment]
Does anyone feel in favour or opposed to any of the topics I proposed? Would anyone also like to teach one of them?

**Comment by oesteban** [comment]
Okay, I made a quick draft for the whole thing. I thought it was limited to one page and then I found out that it is 4, with 4000 characters limit for the outline.

I guess given the time we have (i.e., we need to send it out today), we can just send it as it is and see what happens.

LMKWYT

Esp. interested in feedback from @arokem and @dPys, as I placed their work at the core of the proposal. Also @edickie as I wrote her name as a presenter with mine, and @josephmje if he wants to be the presenter in my place.

**Comment by josephmje** [comment]
Thanks for the push on this @oesteban. I just made a few tiny changes and added a prerequisites section. I'd be happy to have you as presenter on this. I would be interested in contributing to the tutorial content.

**Comment by oesteban** [comment]
For the rest of the folks, the link to Michael's draft is here - https://docs.google.com/document/d/1pl1X6IxVmjhcv0svXCTPJJPn5L3e_yT-IHsykk0wHYc/edit?usp=sharing

**Comment by oesteban** [comment]
Ugh, I now realize that the reference was indeed for the tutorial - sorry for not including. For some reason I thought this was actually a suggestion for dMRIPrep in general.

The proposal is now sent. Fingers crossed! Thank you all :)

**Comment by arokem** [comment]
👏 🎉

**Comment by dPys** [comment]
Hey everyone, this looks awesome! Nice work putting this together.
