### ISSUE TITLE
Telecon, September 24th, 1 PM PST

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#12]
Following up on https://github.com/nipreps/dmriprep/pull/8#issuecomment-531207953, according to the [poll](https://www.when2meet.com/?8108971-Y8OeY), 9/24 at 1 PM PST seems to work for everyone who has filled in their availability so far. Barring any conflicts that arise (please pipe up here), let's set that as the time for our telecon. I have set up a zoom call for this with the following details: 

Join Zoom Meeting: https://washington.zoom.us/j/701882231

One tap mobile
+16699006833,,701882231# US (San Jose)
+16468769923,,701882231# US (New York)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 646 876 9923 US (New York)
Meeting ID: 701 882 231
Find your local number: https://zoom.us/u/adJpEwdYeg

Join by SIP
701882231@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
221.122.88.195 (China)
115.114.131.7 (India)
213.19.144.110 (EMEA)
103.122.166.55 (Australia)
209.9.211.110 (Hong Kong)
64.211.144.160 (Brazil)
69.174.57.160 (Canada)
207.226.132.110 (Japan)
Meeting ID: 701 882 231

**Comment by dPys** [comment]
Works for me!

**Comment by jelleveraart** [comment]
I am happy to join this meeting on the 24th!

**Comment by arokem** [comment]
Summary: 

- PR #14 was discussed. We should make progress towards merging this by the next call. 
- We should start a "wish list" of things that we would like to add/change relative to the existing code (e.g., #8 seems like it's in that direction). 
- While we establish an initial basis of infrastructure and an initial pipeline for smoke-testing, one of the goals of development should be a set of quantitative descriptions of the data as it goes through 
 processing, and establish the decisions made about the processing pipelines. @jelleveraart will flesh this out in a separate issue.
