### ISSUE TITLE
BrainHack Donostia 2020 / Tutorial

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#122]
Please join in developing the materials for the BHD2020 tutorial about dMRIPrep:

https://docs.google.com/document/d/16POXWYSmVw6zLwnZp6K4ZBYPQ3v1tKPOXjHT2GCEGw4/edit?usp=sharing

The idea is to finalize and get #64 fixed by the end of the tutorial, showing the whole process of contributing to an OSS project.

UPDATE: The tutorial will take place online, on November 10, 2020 @ 3pm CET / 9am ET / 6am PT, with a length of 1h 30min.

**Comment by josephmje** [comment]
The tutorial materials were developed here: https://github.com/nipreps/nipreps-book

This repository can be used to further develop material for the upcoming ISBI workshop in April.
