### ISSUE TITLE
Telecon, October 8th, 12:30 PM PST/3:30 PM EST

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#15]
Our next call will take place on October 8th at 12:30 PM PST/3:30 PM EST. 

The link for the call is: https://washington.zoom.us/j/414714117

**Comment by arokem** [comment]
Good seeing everyone!

**Comment by oesteban** [comment]
Added a link to the google doc in the wiki - https://github.com/nipreps/dmriprep/wiki
