### ISSUE TITLE
Use black for python formatting

### ISSUE THREAD

**Issue by richford** [nipreps/dmriprep#16]
### Description of suggestion

I'd like to advocate using [Black](https://pypi.org/project/black/) for python formatting. It's a highly opinionated code formatter that would help contributors think more about the semantic meaning of their contributions rather than the formatting.

This is somewhat an example of [Parkinson's Law](https://en.wikipedia.org/wiki/Law_of_triviality) since we have more important discussions about the roadmap to consider. But the time to set a formatting standard is in the beginning so it might be best to talk about it now.

### What we can do

If we agree on this, I'll submit a PR that adds a pre-commit hook that automatically formats code before a contributor commits a change. I'd also add instructions in the contributing guidelines for how to activate this pre-commit hook when initially cloning the repository.

Contributors can always exempt their section from formatting by adding comments around their code:
```
# fmt: off
if very_long_variable_name is not None and \
 very_long_variable_name.field > 0:
    print("The above formatting is an important choice that I'd like to keep")

# fmt: on
```

**Comment by arokem** [comment]
I'd be +1 for that. I've never used black before, but it seems that it can help streamline things, even  if there are some stylistic things we would still need to enforce in  review (e.g.,  naming conventions mentioned in #14)

**Comment by oesteban** [comment]
My only concern with this is that we add one dependency on the contributor's side. Does it make any sense to replace flake8 with black in #18 instead of a commit hook?

**Comment by richford** [comment]
@oesteban Yep, we could use Black on the CI side by adding
```
pipenv run black --check .
```
to the script section of our `.travis.yml` file. This would replace the flake8 check. I'm in favor of that.

And then we could treat the pre-commit hook as a separate issue. You're right that using the pre-commit hook would add an additional dependency and new contributors will have to type
```bash
pre-commit install
```
after cloning the repo to use the pre-commit hook. This does slightly increases the barrier to contribution. The advantage is that formatting errors are caught before the commit and PR submission so the contributor doesn't have to spend time waiting for travis to spin up and give them a flake8 error. So I see it as an up front cost that pays off over time but I don't have hard data to back up that claim.

If we like the idea of using Black, one compromise is to enforce Black on the travis-ci side of things and then leave the pre-commit hook as an optional thing. That is, we'd put something in the contributing guidelines like "hey, there's this pre-commit hook that you can use that might save you some time. It's not mandatory, but if you want it, here's how to set it up."

**Comment by oesteban** [comment]
Just so you know, we were discussing about black last week in the context of fMRIPrep. We decided to hold on and not use it because it doesn't get along very well with the style we use for nipype's `connect`.

I guess can still use the `# fmt: off/on` for these sections.

Anyway, I thought this info could be interesting for the project.

**Comment by arokem** [comment]
My vote is to hold off here as well. I think that given the additional markup needed with the nipype style, it would just end up being cumbersome.

**Comment by oesteban** [comment]
I have enabled pep8speaks which will write a comment on PRs where flake8 complains, also stating some recommendations to fix the problems.

Let's put this on hold and reconsider if stylistic problems start mounting.
