### ISSUE TITLE
No folder output directory of dwi created 

### ISSUE THREAD

**Issue by nabaruns** [nipreps/dmriprep#165]
* dmriprep version: 0.5.0
* Python version:
* Operating System:

### Description

With the latest docker image, run gets completed with no errors. But no output dwi directory gets created. Only anat, fmap and figures are in dmriprep output directory.

And two text files are generated and stored at input data dwi folder.

### What I Did

sudo docker run -ti --rm -v /home/n/BIDS/05225665_01/:/inputs -v /home/n/dmriprep/05225665_01/:/outputs -v /home/v/freesurfer:/freesurfer -v /home/n/dmriprep/work/:/work nipreps/dmriprep:latest /inputs /outputs participant -w /work --participant-label 0522566501 --fs-license-file /freesurfer/license.txt --ignore fieldmaps --fs-no-reconall --output-spaces MNI152NLin6Asym:res-2

**Comment by josephmje** [comment]
Thank you for raising this issue @nabaruns. `dmriprep` is still in an unstable state, so I would not recommend using it for analysis just yet. However, that doesn't mean that we can't write out the existing outputs to the dwi folder (see #161). I will get on that right away!

**Comment by pandyasneha** [comment]
Dear @oesteban has there been any update on the issue raised above? I tried running dmriprep with both 0.4.0 and 0.5.0 version, and am having similar problem, with no output dwi dir created.

**Comment by oesteban** [comment]
Hi @pandyasneha, unfortunatelly no news - but hopefully that may change soon as the new grant comes through.

**Comment by pandyasneha** [comment]
Thank you so much for the update. Looking forward to it.
