### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by dPys** [nipreps/dmriprep#17]
Articles to consider:
[UKBioBank](https://www.biorxiv.org/content/biorxiv/early/2019/01/04/511964.full.pdf)
[TractoFlow](https://www.biorxiv.org/content/10.1101/631952v1.full)
[HCP](https://www.ncbi.nlm.nih.gov/pubmed/23668970)
[Denoising before or after Interpolation pt. 1](https://community.mrtrix.org/t/denoising-and-unringing-before-eddy/2223)
[Denoising before or after Interpolation pt. 2](https://github.com/nipreps/dmriprep/files/3649689/st-jean_etal_ismrm_2018.pdf)

Summary is that there is more or less broad consensus about the following:
1) Motion outliers (i.e. bad volumes with > +/- 2mm translation and 2 degrees of rotation according [Yendiki et al. 2014](https://www.ncbi.nlm.nih.gov/pubmed/24269273)) should either be removed entirely (ideal) or modeled with a confound regressor (reduces performance of eddy and increases computational burden on denoising, gibbs and bias suppression, etc. because these corrections get wasted on unusable volumes). But most importantly, motion outliers should be detected _first_. 
2) Gibbs Oscillations, if suppressed should happen early in the pipeline (i.e. pre-interpolation)
3) Denoising is a complex issue. On the one hand, it should not be performed post-interpolation (i.e. after eddy correction) because interpolation changes the nature of the underlying noise distribution. On the other hand, if it is performed pre-TOPUP/eddy, then eddy will often fail because the distribution of signal that it uses to model/correct for susceptibility and eddy distortions will be fundamentally different, causing eddy to run for a VERY long time. Jesper indicates that this is due to the eddy hyperparameters struggling to converge on data that is essentially 'too clean'. The best (compromise) solution may therefore be to estimate noise sigma _before_ eddy correction, but then apply denoising based on that sigma estimate _after_ eddy correction. The 2018 conference article above found strong empirical evidence that this strategy led to the best results-- i.e. reduction in noise outliers improved by as much as ~40%. @samuelstjean --please chime in with any corrections or new insights about this somewhat controversial issue ;) No pipeline has fully implemented this strategy as of yet, so it might be a nice way for dmriprep to stand out among the crowd...
4) Bias correction should ideally be performed to remove brightness inhomogeneity (a notoriously bad problem in diffusion imaging), but this step should occur post-interpolation and ideally near the end of the pipeline.
5) Keep everything in native space (at least until after all of the above steps are complete). 

Here's an example of the order of operations that I propose as a starting point (though as I think @jelleveraart rightly noted, variations of theses steps should be evaluated empirically):
![dmriprep_order_of_operations](https://user-images.githubusercontent.com/16432683/65555296-e0b5b480-def1-11e9-9564-8546cfd43d0d.png)

Curious to hear other folks' thoughts and please share any relevant articles that you might find!

Cheers,
@dPys

**Comment by oesteban** [comment]
Thanks for all these references. I'll try to digest them asap and will come back to you :+1:

**Comment by arokem** [comment]
Thanks for putting this together! As far as you can tell, is there a
consensus about Gibbs artifact removal? On the one hand, I know that this
is considered helpful, if you are going to use models that are particularly
sensitive to it. On the other hand, it does look like it sometimes induces
some smoothing. Maybe @rafaelnh can also weigh in here. He implemented the
Gibbs artifcat removal technique that is the recent release of DIPY.

**Comment by dPys** [comment]
You bet. May also be good to get our own @jelleveraart to weigh in as well, given his work on [evaluating the impact of gibbs of dmri](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4915073/) a few years ago.

@jelleveraart-- do you still stand by the conclusion that "the Gibbs ringing effect on the diffusion signal metrics is unexpectedly strong compared to the 9% alterations in the DW images...[and that the] bias occurs even for low bvalue acquisitions, due to the general dependency of the ringing pattern on the b-value."?

**Comment by jelleveraart** [comment]
Hi -


Yes, Gibbs ringing is really challenging, but important artifacts in Diffusion MRI. Every images suffers from it, but diffusion modeling amplified the effect tremendously. Various models are high sensitive to this (e.g. DKI). For a long time, the most common way to mitigate the Gibbs effect was Gaussian smoothing. This is an effective way of dealing suppressing the artifact, but it comes with the cost of blurring of the image.  An alternative way is total variation type of techniques in which you extrapolate the kspace (improved spatial resolution) while enforcing a piecewise constant or linear signal model. This is quite heavy on the computational side, comes with user-dependent variables that are difficult to tune.  During the past years, the work of Kellner et al. has been widely adopted by the dMRI community. It regrids the image on a subvoxel manner to eliminate the effect. It's very effective and easy to use. https://onlinelibrary.wiley.com/doi/10.1002/mrm.26054


All of the above gets more complicated if the data is acquired with partial Fourier and reconstructed using zero-filling (pretty standard with some vendors, e.g. Siemens). In that case, you have a second Gibbs effect, which is harder to model and correct. I am very happy to discuss this in detail.


Overall, subvoxelshift regridding is the state-of-the-art, but a residual artifacts, related to partial Fourier, will remain.





________________________________

**Comment by oesteban** [comment]
@dPys can you add a link to this issue from the google docs, so we keep track of your suggestions but discuss about this there?

https://docs.google.com/document/d/1d2oAy5umm9FFoxJVusCJNmIajlYNrBssX182jO-2k1o/edit?usp=sharing

**Comment by dPys** [comment]
@oesteban  -- You bet!
