### ISSUE TITLE
Remove `dmriprep-data`

### ISSUE THREAD

**Issue by richford** [nipreps/dmriprep#20]
### Description

The old dmriprep had a command line tool called `dmriprep-data` that would download data from public datasets and transform the files to BIDS-format. It worked only on BIDS datasets and the HBN dataset (which is very nearly BIDS compliant) and we had some plans to include other datasets.

With #14 and the clarification of the driving principles, I now think that this should be broken off into a separate tool. As @oesteban pointed out, dmriprep should only support BIDS and BIDS-derivatives for input and output data. And if users need to massage the dataset before that to BIDSify it, then we should point them towards a different tool.

### What actions should be taken

Nothing for now. As we transfer any legacy dmriprep code over to this repo, we should just be sure to leave out any of the old `dmriprep-data` functionality.

I'm happy to submit a PR that removes those lines now, but I wanted to open an issue to see what others think about this first.

**Comment by oesteban** [comment]
This makes a lot of sense. Happy to have a little repo to host that code under the nipreps organization as a useful tool. Happy to mention it (pointing to the new repo here, under nipy or under your user) in the docs.

**Comment by arokem** [comment]
Yeah - I think it's out-of-scope here, and would be useful to maintain
separately.

**Comment by richford** [comment]
Closing as resolved. The old data.py file has been removed and the `S3BidsStudy` object is being added to pyAFQ under `AFQ.data` in [pyAFQ PR #290](https://github.com/yeatmanlab/pyAFQ/pull/290).
