### ISSUE TITLE
No dwi derivatives in output directory

### ISSUE THREAD

**Issue by maryjis** [nipreps/dmriprep#200]
### What happened?

dmriprep version: dMRIPrep v0.5.0+30.g510ed0ea
Python version: Python 3.7.1
Operating System: Docker
 I run the following commands:  git clone https://github.com/nipy/dmriprep, cd dmriprep, make docker
**Description**
With the latest docker image, run gets completed with no errors. But no output dwi directory gets created and only brain mask and bo reference.

Only anat, fmap and figures are in dmriprep output directory.

### What command did you use?

```shell
docker run -ti -v "$PWD/COBRE_BIDS_test:/inputs" -v "$PWD/COBRE_dmri_preproc_test_fs:/outputs"  nipreps/dmriprep:latest dmriprep /inputs /outputs participant --skip-bids-validation --fs-no-reconall.
```

### What version of the software are you running?

 dMRIPrep v0.5.0+30.g510ed0ea

### How are you running this software?

Docker

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

**Comment by oesteban** [comment]
I was recently referred to this issue in a private email. The bad news is that dMRIPrep is currently in a stale state. The good news is that we plan to revamp the development soon.

Please keep an eye on the development and upcoming new releases.
