### ISSUE TITLE
Telecon, October 22nd, 12:30 PM PST/3:30 PM EST

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#23]
Our next call will take place on October 22nd at 12:30 PM PST/3:30 PM EST.

The link for the call is: https://washington.zoom.us/j/577460042

**Comment by oesteban** [comment]
@mattcieslak can you join?

**Comment by mattcieslak** [comment]
Would 4pm EST work?

**Comment by arokem** [comment]
That would work for me. In the worst case, join us midway through.

**Comment by mattcieslak** [comment]
Is this still on?

**Comment by arokem** [comment]
Yes! Since no one else weighed in about moving this, let's keep it at 12:30
PM PT tomorrow. If you can only join at 1 PM (4 PM ET) that's fine and we
can spend a couple of minutes towards the end scheduling the next call for
a time that is convenient for you as well.

**Comment by jelleveraart** [comment]
I will be there

**Comment by oesteban** [comment]
@arokem please post an issue with the next one :)
