### ISSUE TITLE
FR: Conformity check of bvecs and bvals (pure-python implementation)

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#24]
From our shared gDoc:

1. Check for and correct for any bvec/bval corruption (most common ones):
    1. bvec values are often mistakenly entered as 10 instead of 0 (this is a scanner error that I've encountered in at least two open datasets for instance)
    1. Bval says there's a B0 at a given volume index, but that corresponding index in the bvecs is non-zero. This breaks dipy's read_bvals_bvecs.
    1. Length of bvecs does not equal the length of the bvals
    1. character encoding of bvecs is weird (this can happen for instance if this file was manually manipulated in some way by the user, or the data was stored in scientific notation). Delimiter type across bvec columns can also be inconsistent.
    1. We should also come to a consensus about whether to standardize the bvecs as transposed or keep vertical columns. FSL likes them transposed, MRtrix and dipy seem to prefer vertical.

1. Create initial gradient table

I would add the creation of a small reportlet that shows:
- Shells
- Orientations on each shell
- Summary of the diffusion scheme.

For comments on the individual items listed above, please refer to the google doc.

I think this could be written as a Nipype interface

**Comment by josephmje** [comment]
Does the BIDS validator currently do any of these?

**Comment by oesteban** [comment]
Added in the gDoc - yes iv should be checked by the validator and v is imposed by the spec.

**Comment by dPys** [comment]
Good to know.

**Comment by oesteban** [comment]
@dPys is this issue fully implemented now?

**Comment by dPys** [comment]
@oesteban -- I would say so, with the exception of the potential enhancement in #29. If you'd like to close this issue, that would  probably be fine!
