### ISSUE TITLE
Telecon November 19th, 12:30 pm PST / 3:30 pm EST

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#38]
Hi there, 

Oscar Esteban is inviting you to a scheduled Zoom meeting. 

Topic: dMRIPrep
Time: Nov 19, 2019 12:30 PM Pacific Time (US and Canada)

Join from PC, Mac, Linux, iOS or Android: https://stanford.zoom.us/j/300076945

Or iPhone one-tap (US Toll): +18333021536,,300076945# or +16507249799,,300076945#

Or Telephone:
    Dial: +1 650 724 9799 (US, Canada, Caribbean Toll) or +1 833 302 1536 (US, Canada, Caribbean Toll Free)
          
    Meeting ID: 300 076 945
    International numbers available: https://stanford.zoom.us/u/acdjTpQDNo

    Meeting ID: 300 076 945
    SIP: 300076945@zoomcrc.com

**Comment by garikoitz** [comment]
Sorry guys, I think I won't be able to make it today, I will join the next meeting

**Comment by josephmje** [comment]
Sorry I will be away as well. But I have more time on my hands today and tomorrow to get my PR finished.

**Comment by oesteban** [comment]
This one is pretty tight for me too, and given the low feedback I've received (regarding the meeting) I'm guessing it's looking the same for everyone. It also happens that I've been pushing in other fronts that will unlock @josephmje in his PRs.

Why don't we skip this one and keep working via github & mattermost until the next one?

cc @arokem, @dPys, @mattcieslak, @jelleveraart

**Comment by dPys** [comment]
Sounds good to me

**Comment by arokem** [comment]
Sounds good. I will spend that time trying to catch up on the pending PRs.
