### ISSUE TITLE
Prepare test data

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#4]
Prepare a test dataset (perhaps https://openneuro.org/datasets/ds000206 ?)

**Comment by arokem** [comment]
That dataset looks great, with the caveat that only one b-value was used.

**Comment by garikoitz** [comment]
Hi!
the first dataset has been uploaded to OSF and added to circle. We are working in other more complex datasets now, but we need to make them public first...

**Comment by oesteban** [comment]
(more complex == multi-shell)

**Comment by garikoitz** [comment]
Yes, and:
- reverse phase-encoding for all directions
- (working on) field map

**Comment by oesteban** [comment]
Smoke tests are running. I think we can close this and open a new one when we are ready to add more test data.
