### ISSUE TITLE
Telecon this week

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#41]
Hello! I have a conflict tomorrow at our usual time. Any chance we could meet and catch up on Wednesday at 12:30 PM PT?

**Comment by josephmje** [comment]
That time would work for me. I might have to leave around 1 PM PT.

**Comment by oesteban** [comment]
Works for me.

**Comment by garikoitz** [comment]
Works for me too

**Comment by arokem** [comment]
Great! See https://github.com/nipreps/dmriprep/issues/42
