### ISSUE TITLE
Telecon, December 17th

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#44]
Link for the call is here: https://washington.zoom.us/j/144327307

Given this might be our last telecon before the sprint, we should  probably use this call to make a rough schedule for the sprint.

**Comment by oesteban** [comment]
12.30 PST, I assume?

cc/ @nipreps/dmriprep @dPys @richford @garikoitz @mattcieslak @josephmje @jelleveraart

**Comment by arokem** [comment]
Yes. Sorry about the vagueness. I'll be there.

**Comment by dPys** [comment]
Works for me!

**Comment by oesteban** [comment]
Working on a draft for the agenda here - https://hackmd.io/@SdQZX7wbSj6wewa5sQntwg/Bk46asU0B/edit
