### ISSUE TITLE
Workflow figure 1

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#5]
Update fMRIPrep's workflow graph, and upload to repo.

**Comment by oesteban** [comment]
Hey @garikoitz, any updates on this for tomorrow's meeting?

**Comment by garikoitz** [comment]
I'll have it for tomorrow.
Any updates in the WF? Should I still look at the photograph we took of the
board in Seattle? I can add the main steps and review it tomorrow to add
details?

When is it? Tomorrow 12:30 Pacific Time?

**Comment by oesteban** [comment]
> Should I still look at the photograph we took of the board in Seattle? 

I guess so.

> I can add the main steps and review it tomorrow to add details?

Sounds like a plan.





> When is it? Tomorrow 12:30 Pacific Time?

Just sent an invite

**Comment by arokem** [comment]
Sorry: I messed up my schedule and can't make tomorrow's meeting.

Derek and I will be programming together on zoom 10 AM - noon, but I have
to go at noon.

**Comment by oesteban** [comment]
I think we can still use the link, right? Let's do a quick catch-up and
I'll write @arokem with the news.

**Comment by arokem** [comment]
Yes. I believe that the link will still work for you.
