### ISSUE TITLE
Implement QSIPREP's algorithm for b=0 masking

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#57]
In order to replace the current mask workflow (which relies on FSL+AFNI and is designed for BOLD-EPI).

The core of the algorithm is here: https://github.com/PennBBL/qsiprep/blob/a8a1617453b64c2fc7abd9682503aade949322fd/qsiprep/interfaces/nilearn.py#L423

However, the current implementation is not granular and will be hard to maintain in the long term. To simplify that, I'd propose creating a Nipype workflow where each node has a single tool to run. Therefore, these would be the steps to accomplish that:

1. Convert [`calculate_gradmax_b0_mask`](https://github.com/PennBBL/qsiprep/blob/a8a1617453b64c2fc7abd9682503aade949322fd/qsiprep/interfaces/nilearn.py#L307-L420) to a workflow, dropping the report generation step.

  1.1. Reuse the b0 enhancement code from the current implementation ([instead of most of this section](https://github.com/PennBBL/qsiprep/blob/a8a1617453b64c2fc7abd9682503aade949322fd/qsiprep/interfaces/nilearn.py#L337-L343))
  1.2. Use nipype interfaces for ANTs' ``ImageMaths`` (instead of [this](https://github.com/PennBBL/qsiprep/blob/a8a1617453b64c2fc7abd9682503aade949322fd/qsiprep/interfaces/nilearn.py#L346)).
  1.3. Wrap skimage interfaces with nipype
  1.4. Wrap sklearn interfaces with nipype
  1.5. Use dipy's interfaces (e.g. otsu).
  1.6. Replace nilearn's functions with nibabel's whenever possible.

2. Similar process with [`watershed_refined_b0_mask`](https://github.com/PennBBL/qsiprep/blob/a8a1617453b64c2fc7abd9682503aade949322fd/qsiprep/interfaces/nilearn.py#L423-L497)

**Comment by oesteban** [comment]
Is someone willing to take on this one? May I suggest @josephmje ?

**Comment by josephmje** [comment]
Yes, I'd be happy to take this on. I checked with @mattcieslak on Wednesday
and we were sure if you were already working on it.

**Comment by oesteban** [comment]
Glad I asked :)

> Is there something I can include in the docstring to give the proper attribution to Matt?

We need to make sure QSIPREP is cited in the boilerplate. Of course, we can also add a reference in the docstring and add Matt to the creators list of the zenodo file.

**Comment by richford** [comment]
@josephmje, Are you working on this one? I don't want to duplicate effort but would be happy to take it on if you have other stuff on your plate.

**Comment by josephmje** [comment]
hey @richford. i started implementing qsiprep's algorithm but it changed midway through to use the T1w brain mask computed by smriprep (after registering the T1w to the b0). i've tested the existing masking algorithm (a port from fmriprep) on a bunch of my lab's datasets and its been working well for me. i ran into a few situations where ANTS N4 failed and i've been meaning to debug that.

**Comment by oesteban** [comment]
As per our last meeting, we are abandoning this particular algorithm. Because one of the core reasons to start with this is still standing (the use of FSL BET), whenever we find the bandwidth we'll attempt to remove FSL as a dependency.
