### ISSUE TITLE
DOC: Would be nice to have something in https://nipreps.github.io

### ISSUE THREAD

**Issue by arokem** [nipreps/dmriprep#71]
Not really dmriprep-specific, but more generally for the nipreps overall.

It would be nice to have a one-stop shop for information about the nipreps generally. Maybe something that explains what's going on and gives an indication of the relationship between different elements (for example, how do the nipreps relate to each other? And to TemplateFlow?) and provides some pointers out to the various projects.

**Comment by oesteban** [comment]
Okay, just started https://github.com/nipreps/nipreps.github.io - let's follow up there.

**Comment by arokem** [comment]
Yeah - looks like a good start. Thanks!
