### ISSUE TITLE
BUG: Borked reference & mask after sloppy merge

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#90]
Although I'd swear I checked on the reports before merging #81, it seems I didn't look properly or didn't check at all.

https://25-233707741-gh.circle-artifacts.com/0/tmp/THP002/derivatives/dmriprep/sub-THP0005.html#acquisition-GD72_datatype-dwi_desc-brain_run-1_session-THP0005JHU1_suffix-mask

**Comment by josephmje** [comment]
Thanks @oesteban . Will take a look!

**Comment by oesteban** [comment]
Looking at this right now. @josephmje should I hold off? Have you started with this?
