### ISSUE TITLE
Signal Drift Estimation based on low-b volumes

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#93]
1. Modify the existing ExtractB0 interface so that the estimated average signal associated with the b=0 volumes is exposed as an output.
2. Implement a basic exponential fitting (iff sufficient b0s are distributed along time).

**Comment by josephmje** [comment]
Is the [Vos et al., 2017](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.26124) paper a good starting point for this?

**Comment by oesteban** [comment]
1 is done, and we talked about 2 and pushed it away for later in the roadmap. Will reopen or file again when we reach that point.
