### ISSUE TITLE
Head-motion estimation for HMC

### ISSUE THREAD

**Issue by oesteban** [nipreps/dmriprep#94]
A SHOREline-based approach, ported from QSIPREP. In cases where the data are “shelled”, 3dSHORE will be used as the diffusion model. If the data are single-shell, we will use SFM as the diffusion model.

**Comment by dPys** [comment]
#62 #76 #77 #78

**Comment by arokem** [comment]
WIP on this is at : https://github.com/nrdg/hmc

**Comment by oesteban** [comment]
Follow up on this at https://github.com/nipreps/eddymotion
